Add RestoreJobCreator and redefine Kubegres ready state

diff --git a/controllers/spec/template/yaml/BaseConfigMapTemplate.yaml b/controllers/spec/template/yaml/BaseConfigMapTemplate.yaml
--- a/controllers/spec/template/yaml/BaseConfigMapTemplate.yaml
+++ b/controllers/spec/template/yaml/BaseConfigMapTemplate.yaml
@@ -132,6 +132,38 @@ data:
 
     echo "$dt - DB backup completed for Kubegres resource $KUBEGRES_RESOURCE_NAME into file: $backUpFilePath";
 
+  # If you want to create a new Kubegres resource from a restorepoint, this bash scripts restores a
+  # Postgres database into a given destination from a snapshot.
+  #
+  # Assumptions:
+  #   - Name of default database is not equal to the name of database to restore.
+  #   - The snapshot to use contains one database.
+  #
+  # Environment
+  #   POSTGRES_DB: 
+  #   RESTOREPOINT_FILEPATH: 
+  #   BACKUP_TARGET_DB_HOST_NAME: 
+  restore_database.sh: |
+    #!/bin/bash
+    set -e
+
+    dt=$(date '+%d/%m/%Y %H:%M:%S')
+
+    if [ ! -f $RESTOREPOINT_FILEPATH ]; then
+      echo "The specified snapshot '${RESTOREPOINT_FILEPATH}' not found"; 
+    fi
+
+    echo "$dt - Restore of ${POSTGRES_DB} from ${RESTOREPOINT_FILEPATH} has started"
+
+    echo "$dt - Running: pg_restore --no-password -d ${POSTGRES_DB} -h ${BACKUP_TARGET_DB_HOST_NAME} -U postgres --verbose --exit-on-error ${RESTOREPOINT_FILEPATH}"
+    pg_restore --no-password -d ${POSTGRES_DB} -h ${BACKUP_TARGET_DB_HOST_NAME} -U postgres --verbose --exit-on-error ${RESTOREPOINT_FILEPATH}
+
+    if [ $? -ne 0 ]; then
+        echo "Unable to restore the database"
+        exit 1
+    fi
+
+    echo "$dt - DB restored from file ${RESTOREPOINT_FILEPATH} successfully"
 
   # This is the standard Postgres host-based authentication (hba) config applying to Primary and Replica servers.
   # https://www.postgresql.org/docs/current/auth-pg-hba-conf.html
